[Variables]
;Date indicator line color
Clr.Hrl=255,255,255,0

;===== Positioning options =====
;Cell Dimensions - The dimensions of the individual string meters.
C.w=40
C.h=40
;Spacers and bumper
;Vertical space between cells
Space.x=32
;Horizontal space between cells
Space.y=16
;Space on left and right of calendar
Bumper.x=138
;Space on top of calendar
Bumper.top=0
;Space on bottom of calendar
Bumper.bottom=0